/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainRoutesImport } from './routes/MainRoutes'

// Create/Update Routes

const MainRoutesRoute = MainRoutesImport.update({
  id: '/MainRoutes',
  path: '/MainRoutes',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/MainRoutes': {
      id: '/MainRoutes'
      path: '/MainRoutes'
      fullPath: '/MainRoutes'
      preLoaderRoute: typeof MainRoutesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/MainRoutes': typeof MainRoutesRoute
}

export interface FileRoutesByTo {
  '/MainRoutes': typeof MainRoutesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/MainRoutes': typeof MainRoutesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/MainRoutes'
  fileRoutesByTo: FileRoutesByTo
  to: '/MainRoutes'
  id: '__root__' | '/MainRoutes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainRoutesRoute: typeof MainRoutesRoute
}

const rootRouteChildren: RootRouteChildren = {
  MainRoutesRoute: MainRoutesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/MainRoutes"
      ]
    },
    "/MainRoutes": {
      "filePath": "MainRoutes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
