<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFDbContext\AdventureWorksLT2019.EFDbContext.csproj" />
    <ProjectReference Include="..\RepositoriesInterfaces\AdventureWorksLT2019.RepositoriesInterfaces.csproj" />
    <ProjectReference Include="..\Models\AdventureWorksLT2019.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
