<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Models\AdventureWorksLT2019.Models.csproj" />
    <ProjectReference Include="..\Utilities\AdventureWorksLT2019.Utilities.csproj" />
    <ProjectReference Include="..\Shared\AdventureWorksLT2019.Shared.csproj" />
    <ProjectReference Include="..\RepositoriesInterfaces\AdventureWorksLT2019.RepositoriesInterfaces.csproj" />
    <ProjectReference Include="..\ServiceInterfaces\AdventureWorksLT2019.ServiceInterfaces.csproj" />
    <ProjectReference Include="..\EFDbContext\AdventureWorksLT2019.EFDbContext.csproj" />
    <ProjectReference Include="..\MSSqlRepositories\AdventureWorksLT2019.MSSqlRepositories.csproj" />
    <ProjectReference Include="..\Services\AdventureWorksLT2019.Services.csproj" />
  </ItemGroup>

</Project>
